[package]
name = "brainfuck"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.42.0"
cranelift-module = "0.42.0"
cranelift-simplejit = "0.42.0"
