[package]
name = "clock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
tokio = "0.1"
tokio-timer = "0.2"

console = "0.9"
#azul = { git = "https://github.com/maps4print/azul" }

